In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import alphamethods as am

In [2]:
data_arr = np.genfromtxt("../data/Close.csv", delimiter=',')
data_arr

array([[    nan,     nan,     nan, ...,     nan,     nan,     nan],
       [    nan,  20.225,  20.858, ...,  47.72 ,  47.682,  47.295],
       [    nan,  22.355,  22.589, ...,  41.219,  40.509,  40.116],
       ...,
       [    nan,  18.69 ,  18.78 , ...,  27.525,  27.465,  27.088],
       [    nan, 303.66 , 301.2  , ...,  34.65 ,  31.5  ,  32.55 ],
       [    nan,  12.231,  12.305, ...,  14.463,  14.493,  14.532]])

In [3]:
data_arr = np.delete(np.delete(data_arr, 0, 0), 0, 1)
data_arr

array([[ 20.225 ,  20.858 ,  20.612 , ...,  47.72  ,  47.682 ,  47.295 ],
       [ 22.355 ,  22.589 ,  22.637 , ...,  41.219 ,  40.509 ,  40.116 ],
       [  9.3094,   9.1551,   9.0008, ...,  17.816 ,  17.388 ,  17.529 ],
       ...,
       [ 18.69  ,  18.78  ,  18.89  , ...,  27.525 ,  27.465 ,  27.088 ],
       [303.66  , 301.2   , 302.01  , ...,  34.65  ,  31.5   ,  32.55  ],
       [ 12.231 ,  12.305 ,  12.395 , ...,  14.463 ,  14.493 ,  14.532 ]])

In [4]:
am.get_returns(data_arr)

array([[1.0312979 , 0.98820596, 1.0034446 , ..., 0.99561861, 0.99920369,
        0.99188373],
       [1.01046746, 1.00212493, 0.98374343, ..., 0.99934539, 0.98277493,
        0.99029845],
       [0.98342536, 0.98314601, 1.00218869, ..., 1.00462389, 0.97597665,
        1.00810904],
       ...,
       [1.00481541, 1.00585729, 1.01508735, ..., 1.00728244, 0.99782016,
        0.98627344],
       [0.99189883, 1.00268924, 0.96923943, ..., 0.97058824, 0.90909091,
        1.03333333],
       [1.0060502 , 1.0073141 , 0.99596612, ..., 0.99724195, 1.00207426,
        1.00269095]])

In [5]:
print(np.where(am.get_returns(data_arr) >= 8)[0])
print(np.where(am.get_returns(data_arr) >= 8)[1])
print('correct wrong values')
am.correct_wrong_values(data_arr)
print(np.where(am.get_returns(data_arr) >= 8)[0])
print(np.where(am.get_returns(data_arr) >= 8)[1])

[ 178  185  565  569  592  592  772 1315 1528 1657 1805 2144 2313]
[ 901  679 1046  255  177  747  273  566  154  305  855  982  903]
correct wrong values
[569 772]
[254 272]
